version: '3.4'

services:
  apptemplate:
    image: apptemplate
    container_name: apptemplate
    build:
      context: AppTemplate
      dockerfile: Dockerfile
    networks:
      - appnet
    volumes:
      - type: bind
        source: ../TrustedRoots
        target: /usr/local/share/ca-certificates
      - type: bind
        source: ../DevData/apptemplate
        target: /appdata

networks:
  appnet:
    external: true